export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAILURE = 'GET_PROJECTS_FAILURE';
export const GET_ISAUTHENTICATED = 'GET_ISAUTHENTICATED';
export const GET_ISAUTHENTICATED_SUCCESS = 'GET_ISAUTHENTICATED_SUCCESS';
export const GET_ISAUTHENTICATED_FAILURE = 'GET_ISAUTHENTICATED_FAILURE';
